VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IAI"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True


Option Explicit

Public Function Decide(ByVal MyFight As Fight, ByVal Caller As FightBase, ByVal OtherPlayer As FightBase) As MoveDecision
End Function

Public Function AwaitTurn(ByVal MyFight As Fight, ByVal Caller As FightBase, ByVal OtherPlayer As FightBase) As MoveDecision
End Function